### ISSUE TITLE
"Goto end" button should set timeslot to the latest one

### ISSUE THREAD

**Issue by vaclavbartos** [CESNET/SecurityCloudGUI#13]
When I click the ">|" button ("Goto end") in Graph page, it just moves the graph so that it contains the latest timeslot, but the "timeslot indicator" is set to the center of the graph.

In my opinion, it would be much better to also set the selected timeslot to the latest one, i.e. to move the indicator to the right end of the graph.
In case a time interval was selected, it should move the whole interval to the right, so it contains the latest timeslot, but has the same length as before.
(Also, such behavior would be consistent with NfSen)

**Comment by vaclavbartos** [comment]
Similarly, the "<<" and ">>" buttons should move the selected timeslot (or interval) exactly by one day (or what is set as current graph range), not only to move the graph and set the timeslot to its center.

**Comment by nerudaj** [comment]
This issue is now part of issue #17
