### ISSUE TITLE
Terminology: "sources" vs. "channels"

### ISSUE THREAD

**Issue by vaclavbartos** [CESNET/SecurityCloudGUI#14]
As I understand the "Profiles" page, there are "profiles", each consists of several "channels" and data in each channel may come from different "sources" (which are channels of other profiles). I like this terminology, but it's currently not consistent across the GUI.
In particular, in "Graphs" and "Database query", the boxes titled "Sources" should rather be titled "Channels".

**Comment by nerudaj** [comment]
Thank you for pointing that out. The "Sources" title in Db query is a relic of Nfsen terminology.
