### ISSUE TITLE
Inconsistent time formats

### ISSUE THREAD

**Issue by vaclavbartos** [CESNET/SecurityCloudGUI#16]
There are several different time formats used within GUI:

- "16 Jan 2017 - 14:00" in the date field under the graph (and "16 Jan" on the x-axis of the graph)
- "Jan 16 2017 14:00" in the box with selected timeslot/interval, and in the header of "Statistics" page
- "2017-01-16 14:00:00.123" in the database query results

It should be consistent. Preferably the ISO format, i.e. "2017-10-16 14:00".

Also, there is some inconsistency with time zones. When I select a time slot 14:00 and query the database, the resulting flows have timestamps around 13:00. It seems that GUI uses local time but fdistdump prints times in UTC. It should either be unified (this may need changes in fdistdump) or at least the timezone information should be clearly communicated to user.

**Comment by nerudaj** [comment]
That off-by-one hour thingy is something I recall dealing with and most probably I did not find the solution.
I'll see what can be done regarding the format unification.

**Comment by jwrona** [comment]
> It seems that GUI uses local time but fdistdump prints times in UTC.

This is correct. By default fdistdump doesn't convert timestamps to the local time, but there is an option for that (--output-ts-localtime). I don't remember why we made this the default behaviour, do you think it would be better the other way around? I.e. convert from the UTC to the local time and add on option for keeping the timestamps as they are.

**Comment by nerudaj** [comment]
I just found out that the graph library should be able to display UTC time instead of local time so I can unify it either way.

**Comment by jwrona** [comment]
How about to add an option to switch between UTC and local time which would affect both GUI and fdistdump? Local time selection would automatically add the --output-ts-localtime to the fdistdump argument list.

**Comment by nerudaj** [comment]
I can add such thing in the global config for GUI. And in some future iteration when I'll have it in mind, it'll be a user specific option.

**Comment by nerudaj** [comment]
As with the unification of time formats... All times will be printed in the recommended ISO format YYYY-MM-DD HH:mm. There will be exception with the db query which will still show seconds and miliseconds. This is because fdistdump always print miliseconds disregarding strftime format string.

**Comment by vaclavbartos** [comment]
Regarding local time: Supporting both local time and UTC, configurable by a switch in global config, would be great. Local time shuold be probably the default (at least in GUI, fbitdump can keep default to UTC).

Time format: Thanks for changing it to ISO format. Of course, "...HH:mm" was just an example, ISO format can include seconds and milisecodns as well. And they should be present whereever it makes sense, like in the db query, as you said.

**Comment by nerudaj** [comment]
The config.php now containts variable $USE_LOCAL_TIME set to true by default. This forces fdistdump to convert UTC to local. When set to false, fdistdump works in default mode and graphs are forced to use UTC.
If I didn't miss anything, time formats are unified.
