### ISSUE TITLE
The php code runs nonsense shell commands

### ISSUE THREAD

**Issue by thorgrin** [CESNET/SecurityCloudGUI#2]
I see this garbage in my apache error log:
```
sh: Expires:: command not found
sh: Last-Modified:: command not found
sh: D,: command not found
sh: GMT: command not found
sh: Cache-Control:: command not found
sh: Pragma:: command not found
sh: Expires:: command not found
sh: Last-Modified:: command not found
sh: D,: command not found
```

After closer inspection I found that it is probably caused by code at https://github.com/CESNET/SecurityCloudGUI/blob/master/web/php/async/graphCreate.php#L2

Why do you use backslashes there? I believe that you do not really want to execute those strings...

**Comment by nerudaj** [comment]
Fixed in devel branch

This piece of code was copypasted and sometimes it happens to me that regular single slash becomes a backslash. At the time of doing so I had no idea that those two differ in PHP.

**Comment by thorgrin** [comment]
Is the devel branch stable enough to deploy?

**Comment by nerudaj** [comment]
IIRC it should be, it should just contain new undocumented features. Tommorow I'll double check whether the core GUI can be deployed safely and let you know.
Is this issue so serious? I had never experienced any errors in the GUI related to this.

**Comment by thorgrin** [comment]
OK, thanks. I've found other things that do not work as expected (e.g.: selecting channels while doing a query dows not affect anything) so I thought that I'd try the devel version so that I do not report the things, that are already fixed again.

**Comment by nerudaj** [comment]
That channel thingy does not work because ipfixcol does not export data necessary for this task. Those checkboxes are prepared for the future when it will be possible.
