### ISSUE TITLE
Time selection reset

### ISSUE THREAD

**Issue by thorgrin** [CESNET/SecurityCloudGUI#3]
When I change selected profile or select another graph in the Graph window the time selection is set to default (middle of the day). I believe that it should not be changed by this action. I'm running from devel branch now.

**Comment by nerudaj** [comment]
Changing the profile leads to reseting the time selection, that's not a bug, just something nobody cared about until now.
But resetting the time by selecting a different graph, that is a bug, I'll look into it.

**Comment by thorgrin** [comment]
OK. Could you consider the profile change keeping the time selection a feature request as well?

**Comment by nerudaj** [comment]
I'll see whether it would break something or not. If not, then it should not be overly complicated to implement it.

**Comment by nerudaj** [comment]
I've modified the UI in a way that changing the profile does not reset the zoom level and the time window. But changing the graphs did not reset those values as you stated. Can you please test the new version and check this behaviour?

**Comment by thorgrin** [comment]
Thanks, it works as expected now, changing the graphs as well.
