### ISSUE TITLE
Left panel disappears for low resolution screen

### ISSUE THREAD

**Issue by thorgrin** [CESNET/SecurityCloudGUI#4]
The left panel is not shown on my mobile device. I've confirmed with my browser that the panel disappears when window width is less than 750px. Since the panel is crucial to the functioning of the GUI, it either should not disappear at all or it should slide to left side and show a hamburger menu instead.

**Comment by nerudaj** [comment]
The GUI was never intended to be used on the phone. You think it should be even with the mobile unfriendly controls?

**Comment by thorgrin** [comment]
I've noticed that when trying it on the phone during the meeting, however, 750px width limit might be a problem even on a laptop (SXGA+) when the browser window takes only half a screen. If it was something more like 500px, I'd be OK with it.

**Comment by nerudaj** [comment]
Ok, I'll try at least to tweak the width.

**Comment by nerudaj** [comment]
I had modified the sidebar so it is always visible, but for the <768px screen width it shows an alternate version with icons only. I'll try to find better set of icons (default bootstrap icons are not the best for the problem) but it at least keeps the GUI operable for users familiar with it.

**Comment by thorgrin** [comment]
Wonderful, this looks neat. Thanks for attending to this request, it can be closed as far as I'm concerned.
