### ISSUE TITLE
How to close a tab?

### ISSUE THREAD

**Issue by thorgrin** [CESNET/SecurityCloudGUI#5]
There can be multiple tabs in the Database Query window. How do I close the unused tabs? They take space in memory, especially when there is a large result displayed. The only option right now is to refresh whole window, which also resets the time selection (btw, it should not do that).

**Comment by nerudaj** [comment]
There is no way to close tabs right now, internally they are all open just not visible. You can free memory of results by doing querry with small amout of results (I know how stupid it sounds, it's just a tip for now).
Luckily I may have idea how to implement closing of tabs..

**Comment by nerudaj** [comment]
Unfortunately, Bootstrap was not build with anything like close tab (pill) button in mind, so I had to improvise and create an alternative way to close tabs. In addition there is a button for just clearing the results (and thus freeing the memory). Layout hasn't been tested on all resolutions yet, but the functionality is there. Let me know if you find any problem here.
