### ISSUE TITLE
Graph is not redrawn

### ISSUE THREAD

**Issue by cejkato2** [CESNET/SecurityCloudGUI#7]
The main graph disappeared after switching between statistics and graph.
This probably happens when I change size of window on statistics tab and then I switch back to the graph tab.
Screenshot attached.
![snimek z 2017-01-09 18-53-02](https://cloud.githubusercontent.com/assets/205818/21777069/990cf544-d69d-11e6-8662-41d9e4d77f86.png)

**Comment by nerudaj** [comment]
This is actually addressed in the readme in the troubleshooting section. I know about this issue, I know exactly what causes it, I just don't know how to fix it (yet, hopefully). Simply put, if the window is resized by any mean and the GUI is not on the Graphs tab, the underlying library for drawing graphs will get confused and breaks.

**Comment by nerudaj** [comment]
Solution has been pushed to devel branch. So far I was able to confirm it's functionality only in Firefox. Graph should not break after resizing the window while being on a tab other than Graphs. Cursor still gets confused on most occassions but forcing the cursor to reload itself (by changing graph resolution, or clicking to the left edge of the graph area or moving to different time slot by datetimepicker) will fix this (which is not ideal but still much better than reloading the whole page).

**Comment by nerudaj** [comment]
A much better solution has been pushed to devel branch. Now it should behave as expected (tested in IE and Firefox).
NOTE: Resizing the browser will result in reseting the cursor to the center of the currently shown area.
